### ISSUE TITLE
Add jammy?

### ISSUE THREAD

**Issue by MarcoFalke** [opencollab/llvm-jenkins.debian.net#11]
Not sure if this is too early, but Ubuntu Jammy could be added. Happy to help, but I couldn't figure out how to add it myself.

**Comment by sylvestre** [comment]
yeah, it is quite early 
do you need it?

**Comment by MarcoFalke** [comment]
No, I don't strictly need it. Sometimes I "accidentally" end up on Jammy and then realize I need to use Focal.

**Comment by sylvestre** [comment]
https://discourse.llvm.org/t/apt-llvm-org-14-branch-ubuntu-jammy/60345
