### ISSUE TITLE
clangd-8 package missing for Debian buster

### ISSUE THREAD

**Issue by ChristianKuehnel** [opencollab/llvm-jenkins.debian.net#6]
When running some tests for my installation scripts, I noticed, that the repo for Debian buster does not contain the `clangd-8` package, while the other distributions have that.

http://apt.llvm.org/buster/pool/main/l/llvm-toolchain-8/
vs
http://apt.llvm.org/stretch/pool/main/l/llvm-toolchain-8/

I did not yet check for the other clangd versions

**Comment by sylvestre** [comment]
Fixed, I started a new build 
http://apt.llvm.org/buster/pool/main/l/llvm-toolchain-8/
Could you please enter bugs  https://bugs.llvm.org/enter_bug.cgi?product=Packaging ?
thanks
